# This workflow builds and pushes a Node.js application to an Azure Web App when a commit is pushed to the development branch.
# This workflow assumes you have already created the target Azure App Service web app and configured its managed identity.
# For instructions, see https://docs.microsoft.com/en-us/azure/app-service/overview-managed-identity

# To configure this workflow:
#
# 1. Enable system-assigned managed identity for your Azure Web App.
# 2. Assign the managed identity the necessary roles (e.g., Contributor) on your Azure subscription or resource group.
# 3. Create secrets in your GitHub repository for AZURE_OBJECT_ID, AZURE_TENANT_ID, and AZURE_SUBSCRIPTION_ID.

on:
  push:
    branches: [ "development" ]
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: app-FarmersFriend-dev    # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: '.'              # set this to the path to your web app project, defaults to the repository root
  NODE_VERSION: '20.x'                        # set this to the Node.js version to use

permissions:
  contents: read
  id-token: write  # Needed for managed identity login

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies and build
        run: |
          npm install
          CI=false npm run build --if-present
          # CI=false npm run test --if-present  # Commenting out test step

      - name: Create artifact archive
        run: |
          tar -czf node-app.tar.gz ./*

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: node-app.tar.gz

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Development'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Login to Azure using managed identity
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_584245B068C241C7836F8338EF2D61DA }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_94A5B2260D9743138CD2C0B416296D91 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_0374F77CE0784FB38A6F509B9B6A7BE9 }}

      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: node-app

      - name: Extract artifact
        run: |
          tar -xzf node-app.tar.gz

      - name: Deploy to Azure WebApp
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
