name: Build and deploy Node.js app to Azure Web App - app-FarmersFriend-dev

on:
  push:
    branches:
      - development
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: |
          npm install
          CI=false npm run build --if-present

      - name: Build the React app
        run: CI=false npm run build --if-present

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: node-app-build
          path: build/

      - name: Upload package.json and package-lock.json
        uses: actions/upload-artifact@v3
        with:
          name: node-app-package
          path: |
            package.json
            package-lock.json

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: node-app-build
          path: ./build

      - name: Download package.json and package-lock.json
        uses: actions/download-artifact@v3
        with:
          name: node-app-package
          path: .

      - name: Install dependencies in deployment environment
        run: npm ci

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: app-FarmersFriend-dev
          slot-name: 'Production'
          package: ./build
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_E3D3A708C7DF4C0F8AE33E4FEB7129AD }}
