name: Build and deploy Node.js app to Azure Web App - app-FarmersFriend-qa

on:
  push:
    branches:
      - development
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Cache Node.js modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.npm
            node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm install

      - name: Build the app
        run: CI=false npm run build --if-present

      - name: Zip artifact for deployment
        run: zip -r release.zip ./*

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Clean wwwroot using Kudu
        run: |
          az webapp config appsettings set --name app-FarmersFriend-qa --resource-group rg-FarmersFriend-qa --settings SCM_DO_BUILD_DURING_DEPLOYMENT=true
          KUDU_USER=$(az webapp deployment list-publishing-profiles --name app-FarmersFriend-qa --resource-group <your-resource-group> --query '[0].publishingUserName' -o tsv)
          KUDU_PASS=$(az webapp deployment list-publishing-profiles --name app-FarmersFriend-qa --resource-group <your-resource-group> --query '[0].publishingPassword' -o tsv)
          KUDU_URL=https://app-FarmersFriend-qa.scm.azurewebsites.net/api/command
          curl -u $KUDU_USER:$KUDU_PASS -X POST -d '{ "command": "rm -rf /home/site/wwwroot/*" }' $KUDU_URL

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'app-FarmersFriend-qa'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_B9100A944703400DA6F41E34DA61CB97 }}
          package: .
