name: Build and deploy Node.js app to Azure Web App - app-FarmersFriend-dev

on:
  push:
    branches:
      - development
  workflow_dispatch:

# There are two jobs in this workflow - build and deploy
jobs:
  # Builds the application for production. 
  # You should configure this environment as close as possible to the production environment, e.g. using Ubuntu for Linux apps, using the same Node version
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies, build
        run: |
          npm install
          CI=false npm run build --if-present
          # npm run test --if-present
          # Other scripts if configured should be added here, such as linting, formatting

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: build/ # Upload only the build directory
 
  # Deploy the application to Azure
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: node-app
          path: ./build # Download to build directory

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: app-FarmersFriend-dev
          slot-name: 'Production'
          package: ./build # Deploy the build directory
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_E3D3A708C7DF4C0F8AE33E4FEB7129AD }}
